"""
A dictionary of words and questions for the hangman game.
"""

WORDS = {
    "bash": "A command language and shell for Unix-like operating systems.",
    "kernel": "The core component of an operating system.",
    "python": "A popular high-level programming language.",
    "repository": "A central location in which data is stored and managed.",
    "command": "An instruction given to a computer program.",
    "powershell": "A task automation and configuration management framework from Microsoft.",
    "registry": "A hierarchical database that stores low-level settings for the Microsoft Windows operating system.",
    "ram": "A form of computer memory that can be read and changed in any order.",
    "cpu": "The electronic circuitry that executes instructions comprising a computer program.",
    "gpu": "A specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images.",
    "ssd": "A solid-state storage device that uses integrated circuit assemblies to store data persistently.",
    "hdd": "An electro-mechanical data storage device that stores and retrieves digital data using magnetic storage.",
    "linux": "A family of open-source Unix-like operating systems based on the Linux kernel.",
    "windows": "A group of several proprietary graphical operating system families, all of which are developed and marketed by Microsoft.",
    "bios": "Firmware used to perform hardware initialization during the booting process.",
    "uefi": "A specification that defines a software interface between an operating system and platform firmware.",
    "driver": "A computer program that operates or controls a particular type of device that is attached to a computer.",
    "malware": "Software that is specifically designed to disrupt, damage, or gain unauthorized access to a computer system.",
    "firewall": "A network security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules.",
    "router": "A networking device that forwards data packets between computer networks.",
    # Linux Commands
    "ls": "What command lists the contents of a directory in Linux?",
    "pwd": "What command prints the current working directory in Linux?",
    "cd": "What command is used to change the current directory in Linux?",
    "mkdir": "What command is used to create a new directory in Linux?",
    "rmdir": "What command is used to remove an empty directory in Linux?",
    "cp": "What command is used to copy files or directories in Linux?",
    "mv": "What command is used to move or rename files or directories in Linux?",
    "rm": "What command is used to delete files or directories in Linux?",
    "touch": "What command is used to create an empty file in Linux?",
    "cat": "What command is used to display the content of a file in Linux?",
    "grep": "What command is used to search for patterns in files in Linux?",
    "chmod": "What command is used to change file permissions in Linux?",
    "chown": "What command is used to change file ownership in Linux?",
    "sudo": "What command is used to execute a command as the superuser in Linux?",
    "tar": "What command is used to create and extract archive files in Linux?",
    "ping": "What command is used to check network connectivity in Linux?",
    "ssh": "What command is used for remote login using Secure Shell in Linux?",
    "wget": "What command is used to retrieve files from the internet in Linux?",
    "man": "What command is used to display the manual page for a command in Linux?",
    "history": "What command is used to display a list of previously executed commands in Linux?",
    "awk": "A powerful pattern-scanning and processing language in Linux.",
    "sed": "A stream editor for filtering and transforming text in Linux.",
    "sort": "What command sorts lines of text files in Linux?",
    "wc": "What command counts lines, words, and characters in files in Linux?",
    "diff": "What command compares two files line by line and shows the differences in Linux?",
    "useradd": "What command creates a new user account in Linux?",
    "passwd": "What command changes a user's password in Linux?",
    "scp": "What command is used for securely copying files between hosts on a network in Linux?",
    "curl": "A tool to transfer data from or to a server, supporting various protocols in Linux.",
    "zip": "What command is used to compress files into a .zip archive in Linux?",
    "unzip": "What command is used to decompress files from a .zip archive in Linux?",
    "gzip": "What command is used to compress or decompress files using the GNU zip algorithm in Linux?",
    "gunzip": "What command is used to decompress files compressed with gzip in Linux?",
    "apt": "The package manager for Debian/Ubuntu-based systems.",
    "yum": "The package manager for Red Hat/CentOS-based systems.",
    "pacman": "The package manager for Arch Linux.",
    "alias": "Creates a shortcut to a command.",
    "basename": "Strips directory and suffix from filenames.",
    "cal": "Displays a calendar.",
    "cmp": "Compares two files byte by byte.",
    "comm": "Compares two sorted files line by line.",
    "crontab": "Schedules a command to run at a later time.",
    "csplit": "Splits a file into sections determined by context lines.",
    "declare": "Declares variables and gives them attributes.",
    "dd": "Converts and copies a file.",
    "df": "Displays free disk space.",
    "dmesg": "Prints kernel and driver messages.",
    "du": "Estimates file space usage.",
    "env": "Displays, sets, or removes environment variables.",
    "eval": "Evaluates several commands/arguments.",
    "exec": "Executes a command.",
    "exit": "Exits the shell.",
    "export": "Sets an environment variable.",
    "factor": "Prints prime factors.",
    "fg": "Sends job to foreground.",
    "file": "Determines file type.",
    "find": "Finds files.",
    "fmt": "Simple optimal text formatter.",
    "fold": "Wraps each input line to fit in specified width.",
    "free": "Displays the amount of free and used memory in the system.",
    "gawk": "Pattern scanning and processing language.",
    "getopts": "Parses positional parameters.",
    "hash": "Remembers the full path of a name argument.",
    "head": "Outputs the first part of a file.",
    "hostname": "Prints or sets the system's host name.",
    "id": "Prints real and effective user and group IDs.",
    "ifconfig": "Configures a network interface.",
    "inotifywait": "Wait for changes to files.",
    "install": "Copies files and sets attributes.",
    "iostat": "Reports Central Processing Unit (CPU) statistics and input/output statistics for devices and partitions.",
    "ip": "Show / manipulate routing, devices, policy routing and tunnels.",
    "jobs": "Lists active jobs.",
    "join": "Joins lines of two files on a common field.",
    "kill": "Stops a process.",
    "killall": "Kills processes by name.",
    "last": "Shows a listing of last logged in users.",
    "ldd" : "Prints shared library dependencies.",
    "less": "A file pager.",
    "let": "Performs arithmetic on shell variables.",
    "link": "Creates a hard link to a file.",
    "ln": "Creates a symbolic link to a file.",
    "local": "Creates a local variable.",
    "locate": "Finds files by name.",
    "logname": "Prints the user's login name.",
    "look": "Displays lines beginning with a given string.",
    "lpc": "Line printer control program.",
    "lpr": "Off line print.",
    "lsof": "Lists open files.",
    "ltrace": "A library call tracer.",
    "make": "Maintains, updates, and regenerates groups of programs.",
    "mktemp": "Creates a temporary file or directory.",
    "more": "A file pager.",
    "mount": "Mounts a file system.",
    "mtools": "Utilities to access MS-DOS disks.",
    "mtr": "A network diagnostic tool.",
    "mutt": "A small but very powerful text-based mail client.",
    "nc": "Arbitrary TCP and UDP connections and listens.",
    "netcat": "A networking utility for reading from and writing to network connections using TCP or UDP.",
    "nethogs": "A small 'net top' tool.",
    "nice": "Runs a program with modified scheduling priority.",
    "nl": "Numbers lines of files.",
    "nm": "Lists symbols from object files.",
    "nohup": "Runs a command immune to hangups, with output to a non-tty.",
    "nslookup": "Queries Internet name servers interactively.",
    "objdump": "Displays information from object files.",
    "od": "Dumps files in octal and other formats.",
    "openssl": "A robust, commercial-grade, and full-featured toolkit for the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols.",
    "paste": "Merges lines of files.",
    "patch": "Applies a diff file to an original.",
    "pathchk": "Checks whether file names are valid or portable.",
    "pax": "Portable archive interchange.",
    "pgrep": "Looks up processes based on name and other attributes.",
    "pkill": "Signals processes based on name and other attributes.",
    "popd": "Removes entries from the directory stack.",
    "pr": "Converts text files for printing.",
    "printcap": "Printer capability database.",
    "printenv": "Prints all or part of environment.",
    "printf": "Formats and prints data.",
    "ps": "Reports a snapshot of the current processes.",
    "pushd": "Saves and then changes the current directory.",
    "pv": "Monitors the progress of data through a pipe.",
    "read": "Reads a line from standard input.",
    "readelf": "Displays information about ELF files.",
    "readonly": "Marks variables as read-only.",
    "renice": "Alters priority of running processes.",
    "remsync": "Synchronize remote files.",
    "return": "Returns from a shell function.",
    "rev": "Reverses lines of a file.",
    "rsync": "A fast, versatile, remote (and local) file-copying tool.",
    "screen": "A full-screen window manager that multiplexes a physical terminal between several processes.",
    "script": "Makes a typescript of a terminal session.",
    "sdiff": "Side-by-side merge of file differences.",
    "seq": "Prints a sequence of numbers.",
    "set": "Sets or unsets shell variables and functions.",
    "sftp": "Secure file transfer program.",
    "shift": "Shifts positional parameters.",
    "shred": "Overwrites a file to hide its contents, and optionally deletes it.",
    "size": "Lists section sizes and total size.",
    "sleep": "Delays for a specified amount of time.",
    "source": "Executes commands from a file in the current shell.",
    "split": "Splits a file into pieces.",
    "ss": "Another utility to investigate sockets.",
    "stat": "Displays file or file system status.",
    "strace": "Traces system calls and signals.",
    "strings": "Prints the strings of printable characters in files.",
    "stty": "Changes and prints terminal line settings.",
    "su": "Runs a command with substitute user and group ID.",
    "sum": "Checksums and counts the blocks in a file.",
    "sync": "Flushes file system buffers.",
    "sysctl": "Configures kernel parameters at runtime.",
    "tac": "Concatenates and prints files in reverse.",
    "tail": "Outputs the last part of a file.",
    "tee": "Reads from standard input and writes to standard output and files.",
    "test": "Checks file types and compares values.",
    "time": "Runs programs and summarizes system resource usage.",
    "timeout": "Runs a command with a time limit.",
    "times": "Prints the accumulated user and system times.",
    "tload": "Prints a graph of the system load average to a terminal.",
    "top": "Displays Linux processes.",
    "tput": "Initializes a terminal or queries terminfo database.",
    "tr": "Translates or deletes characters.",
    "tracepath": "Traces path to a network host discovering MTU along this path.",
    "traceroute": "Prints the route packets trace to network host.",
    "trap": "Traps signals.",
    "true": "Does nothing, successfully.",
    "tty": "Prints the file name of the terminal connected to standard input.",
    "ulimit": "Gets and sets user limits.",
    "umask": "Gets or sets the file mode creation mask.",
    "umount": "Unmounts file systems.",
    "uname": "Prints system information.",
    "unexpand": "Converts spaces to tabs.",
    "uniq": "Reports or omits repeated lines.",
    "units": "Converts units from one scale to another.",
    "unlink": "Calls the unlink function to remove the specified file.",
    "unset": "Unsets shell variables and functions.",
    "unshare": "Runs a program with some namespaces unshared from the parent.",
    "until": "Executes commands as long as a condition is false.",
    "uptime": "Tells how long the system has been running.",
    "users": "Prints the user names of users currently logged in.",
    "uucp": "Unix to Unix copy.",
    "uudecode": "Decodes a file created by uuencode.",
    "uuencode": "Encodes a binary file.",
    "vdir": "Lists directory contents.",
    "vi": "A screen-oriented (visual) display editor.",
    "vmstat": "Reports virtual memory statistics.",
    "w": "Shows who is logged on and what they are doing.",
    "wait": "Waits for a process to complete.",
    "watch": "Executes a program periodically, showing output fullscreen.",
    "whatis": "Displays one-line manual page descriptions.",
    "whereis": "Locates the binary, source, and manual page files for a command.",
    "which": "Shows the full path of (shell) commands.",
    "while": "Executes commands as long as a condition is true.",
    "who": "Shows who is logged on.",
    "whoami": "Prints effective user ID.",
    "write": "Sends a message to another user.",
    "xargs": "Builds and executes command lines from standard input.",
    "xxd": "Makes a hexdump or does the reverse.",
    "yes": "Outputs a string repeatedly until killed.",
    "zcat": "Decompresses and concatenates files to standard output.",
    "zcmp": "Compares compressed files.",
    "zdiff": "Compares compressed files.",
    "zforce": "Forces a '.gz' extension on all gzip files.",
    "zgrep": "Searches possibly compressed files for a regular expression.",
    "zless": "A file pager for compressed files.",
    "zmore": "A file pager for compressed files.",
    "znew": "Recompresses .Z files to .gz files.",
    # Windows Commands
    "dir": "What command lists the contents of a directory in Windows?",
    "copy": "What command is used to copy files in Windows?",
    "del": "What command is used to delete files in Windows?",
    "ren": "What command is used to rename a file or directory in Windows?",
    "move": "What command is used to move files or directories in Windows?",
    "type": "What command is used to display the content of a text file in Windows?",
    "cls": "What command is used to clear the screen in Windows Command Prompt?",
    "systeminfo": "What command displays detailed system information in Windows?",
    "tasklist": "What command lists all running processes in Windows?",
    "taskkill": "What command is used to terminate a process in Windows?",
    "shutdown": "What command is used to shut down or restart the computer in Windows?",
    "ipconfig": "What command displays IP configuration in Windows?",
    "tracert": "What command traces the route to a destination in Windows?",
    "netstat": "What command displays network statistics in Windows?",
    "chkdsk": "What command is used to check a disk for errors in Windows?",
    "sfc": "What command is used to scan and repair system files in Windows?",
    "xcopy": "What command copies files and directory trees in Windows?",
    "robocopy": "What is the robust file copy command in Windows?",
    "fc": "What command compares two files and highlights differences in Windows?",
    "findstr": "What command searches for patterns in files in Windows?",
    "replace": "What command replaces one or more files with files from another location in Windows?",
    "tree": "What command displays a graphical representation of the directory structure in Windows?",
    "driverquery": "What command lists all installed device drivers and their properties in Windows?",
    "powercfg": "What command manages power settings in Windows?",
    "gpupdate": "What command updates group policies in Windows?",
    "gpresult": "What command displays the Resultant Set of Policy (RSoP) information in Windows?",
    "regedit": "What command launches the Windows Registry Editor?",
    "msinfo32": "What command opens the System Information window in Windows?",
    "netsh": "What command is used to configure and control network components in Windows?",
    "arp": "What command shows and modifies entries in the Address Resolution Protocol (ARP) cache in Windows?",
    "pathping": "What command combines ping and tracert functionalities for detailed network path diagnostics in Windows?",
    "telnet": "What command establishes a Telnet connection in Windows (if the client is installed)?",
    "ftp": "What command transfers files to and from an FTP server in Windows?",
    "route": "What command displays and modifies the network routing table in Windows?",
    # PowerShell Commands
    "get-command": "What PowerShell cmdlet discovers and explores available commands?",
    "get-help": "What PowerShell cmdlet provides assistance and information about commands?",
    "get-process": "What PowerShell cmdlet retrieves information about running processes?",
    "stop-process": "What PowerShell cmdlet stops one or more running processes?",
    "get-service": "What PowerShell cmdlet retrieves information about system services?",
    "get-childitem": "What PowerShell cmdlet gets the files and folders in a file system drive (aliased as ls)?",
    "copy-item": "What PowerShell cmdlet copies files and directories?",
    "move-item": "What PowerShell cmdlet moves an item from one location to another?",
    "remove-item": "What PowerShell cmdlet deletes files and folders (aliased as rm)?",
    "set-location": "What PowerShell cmdlet sets the current working location (aliased as cd)?",
    "get-content": "What PowerShell cmdlet gets the contents of a file (aliased as cat)?",
    "set-content": "What PowerShell cmdlet writes or replaces the content of an item?",
    "add-content": "What PowerShell cmdlet appends content to a file?",
    "new-item": "What PowerShell cmdlet creates a new item (e.g., file, directory)?",
    "rename-item": "What PowerShell cmdlet renames an item?",
    "invoke-command": "What PowerShell cmdlet runs commands on local or remote computers?",
    "invoke-expression": "What PowerShell cmdlet runs commands or expressions on the local computer?",
    "set-executionpolicy": "What PowerShell cmdlet modifies the script execution policy?",
    "test-connection": "What PowerShell cmdlet checks network connectivity (similar to ping)?",
    "get-eventlog": "What PowerShell cmdlet accesses Windows event logs?",
    "where-object": "What PowerShell cmdlet selects objects from a collection based on their property values?",
    "select-object": "What PowerShell cmdlet selects an object or a group of objects with defined properties?",
    "convertto-html": "What PowerShell cmdlet converts objects into HTML format?",
    "out-file": "What PowerShell cmdlet sends output to a file?",
    # Hardware Terms
    "motherboard": "What is the main circuit board of a computer called?",
    "psu": "What component converts AC power to DC power for the computer?",
    "keyboard": "What is the primary input device for typing?",
    "mouse": "What is the pointing device used to control the cursor on a screen?",
    "monitor": "What is the main visual display unit of a computer?",
    "printer": "What device is used to create a physical copy of a digital document?",
    "scanner": "What device is used to convert a physical document into a digital one?",
    "microphone": "What device is used to record audio?",
    "speakers": "What devices are used to listen to audio from a computer?",
    "nic": "What card provides a physical connection to a network?",
    "modem": "What device is used to connect to the internet over a phone line?",
    "wifi": "What technology allows devices to connect to a network without cables?",
    "ethernet": "What is the standard for wired computer networking?",
    "bit": "The smallest unit of data in a computer.",
    "byte": "A unit of data that is eight binary digits long.",
    "kilobyte": "A unit of memory or data storage equal to 1,024 bytes.",
    "megabyte": "A unit of information equal to one million bytes.",
    "gigabyte": "A unit of information equal to one billion bytes.",
    "terabyte": "A unit of information equal to one trillion bytes.",
    "ddr": "A type of RAM that transfers data twice per clock cycle.",
    "dram": "A type of RAM that stores each bit of data on a separate capacitor.",
    "rom": "Memory that retains its data even when power is off.",
    "firmware": "Software embedded in hardware devices.",
    "bus": "A set of parallel connectors that join components together.",
    "heatsink": "A block of metal fins designed to draw heat away from components.",
    "clockspeed": "The speed at which a CPU or RAM operates.",
    "vga": "A standard connector for computers to displays.",
    "dvi": "A video display interface used to connect a video source to a display device.",
    "hdmi": "A standard for connecting high-definition video devices.",
    "switch": "A device that connects multiple wired devices on a network.",
    "lan": "A network that connects devices within a limited area.",
    "ipaddress": "A unique numerical label that identifies each device on a network.",
    "macaddress": "A unique hardware identifier assigned to a device's network interface controller.",
    # Software Terms
    "agile": "What is an iterative approach to software development?",
    "algorithm": "What is a set of rules to be followed in calculations or other problem-solving operations?",
    "api": "What allows different software applications to communicate with each other?",
    "bug": "What is an error, flaw or fault in a computer program?",
    "compiler": "What program translates source code into machine code?",
    "database": "What is a structured set of data held in a computer?",
    "debugging": "What is the process of finding and resolving defects or problems within a computer program?",
    "deployment": "What is the process of making a software system available for use?",
    "framework": "What provides a standard way to build and deploy applications?",
    "git": "What is a popular distributed version control system?",
    "gui": "What type of user interface allows users to interact with electronic devices through graphical icons?",
    "ide": "What does IDE stand for in software development?",
    "library": "What is a collection of non-volatile resources used by computer programs?",
    "oop": "What programming paradigm is based on the concept of 'objects'?",
    "os": "What is the system software that manages computer hardware, software resources, and provides common services for computer programs?",
    "refactoring": "What is the process of restructuring existing computer code without changing its external behavior?",
    "sdk": "What does SDK stand for?",
    "sql": "What language is used for managing data held in a relational database management system?",
    "ux": "What does UX stand for in design?",
    "ui": "What does UI stand for in design?",
    "scrum": "A project management methodology for effective team collaboration.",
    "sprint": "A short, time-boxed period during which a Scrum team works to complete a set amount of work.",
    "tdd": "A software development approach where developers write tests before writing the actual code.",
    "waterfall": "A traditional software development approach where each phase of the SDLC follows a linear sequence.",
    "backend": "The part of a software application not visible to the user.",
    "bigonotation": "A mathematical notation describing the performance or complexity of an algorithm.",
    "blockchain": "A distributed ledger technology where data is stored in linked blocks.",
    "boolean": "A data type with only two possible values (true/false).",
    "buffer": "A temporary storage area for data.",
    "client-server": "An architectural model where clients request and receive services from a centralized server.",
    "cloudcomputing": "The delivery of on-demand computing services over the Internet.",
    "dependencyinjection": "A design pattern used to implement inversion of control.",
    "functionalprogramming": "A programming paradigm where programs are constructed by applying and composing functions.",
    "highlevel-language": "A programming language with strong abstraction from the details of the computer.",
    "lowlevel-language": "A programming language that provides little or no abstraction from a computer's instruction set architecture.",
    "machinelearning": "A field of artificial intelligence that focuses on developing algorithms that allow computers to learn.",
    "mvc": "An architectural pattern that separates an application into three main logical components: Model, View, and Controller.",
    "virtualmachine": "An emulation of a computer system that provides the functionality of a physical computer.",
    "webservice": "A software system that allows interoperable machine-to-machine communication over a network.",
    "acceptancetesting": "Testing that occurs on the client side to ensure the software meets business requirements.",
    "alphatesting": "Software testing performed by internal staff before making it available to external testers.",
    "automatedtesting": "Using software to execute tests automatically.",
    "betatesting": "The second phase of software testing in which a sample of the intended audience tries the product.",
    "functionaltesting": "Testing to verify that each function of the software application operates in conformance with the requirements.",
    "integrationtesting": "Testing where individual software modules are combined and tested as a group.",
    "performancetesting": "A form of testing that examines the speed, response time, and usage of software.",
    "qualityassurance": "The process of ensuring that software products meet specified quality standards.",
    "unittest": "Testing specific pieces of code in a system, typically individual functions or methods.",
    "usabilitytesting": "Evaluates the user-friendliness and effectiveness of software by testing it with real users.",
    "userstory": "An informal description of a software feature, written from the perspective of the end-user.",
    "usecase": "A written documentation of how users navigate a system or website.",
    "pullrequest": "A mechanism for developers to notify team members that they have completed a feature or bug fix.",
    "storypoints": "An estimation of task complexity in the Agile approach.",
    "authentication": "The process of verifying the identity of a user or system.",
    "authorization": "The process of determining a user's actions after authentication.",
    "cache": "A temporary storage area that stores frequently accessed data for faster retrieval.",
    "crm": "Software that helps businesses manage customer interactions, sales, and support.",
    "css": "A style sheet language that organizes HTML elements.",
    "dataabstraction": "A principle of data modeling that emphasizes the separation between the external interface and internal implementation.",
    "erp": "Software that integrates various business processes into a single system.",
    "lowcode": "Platforms that allow users to build applications with minimal hand-coding.",
    "saas": "A software delivery model where applications are hosted online and accessed via subscription.",
    "scalability": "A system's ability to handle growing amounts of work.",
    "schema": "The structure that defines how data is organized in a database.",
    "systemintegration": "Involves connecting different software systems to work together as a cohesive unit.",
    "uml": "A standardized general-purpose modeling language in the field of software engineering.",
    # Linux Terms
    "gnu": "What does GNU stand for?",
    "opensource": "What is software with source code that anyone can inspect, modify, and enhance called?",
    "filesystem": "What is the system an OS uses to control how data is stored and retrieved?",
    "process": "What is an instance of a computer program that is being executed?",
    "root": "What is the top-level directory of a Linux file system?",
    "home": "What is the directory that contains a user's personal files?",
    "cli": "What is a text-based user interface (UI) used to view and manage computer files?",
    "shell": "What is a user interface for access to an operating system's services?",
    "terminal": "What is the program that opens a window and lets you interact with the shell?",
    "distro": "What is a specific version of a Linux operating system called?",
    "packagemanager": "What tool automates the process of installing, upgrading, and removing software packages?",
    "dependencies": "What are the other packages that a particular package needs to function correctly?",
    "binary": "What is a file that contains information in a format that is not human-readable?",
    "cron": "What is the time-based job scheduler in Unix-like operating systems?",
    "daemon": "What is a background process that runs without user interaction?",
    "x11": "What is the windowing system used by many Linux distributions?",
    # Windows Terms
    "cortana": "What is Microsoft's virtual assistant?",
    "explorer": "What is the file manager in Windows?",
    "taskmanager": "What utility in Windows shows the programs, processes, and services that are currently running on your computer?",
    "controlpanel": "What is the central place to manage settings in Windows?",
    "bitlocker": "What is the full-disk encryption feature in Windows?",
    "defender": "What is the built-in antivirus software in Windows?",
    "activex": "What is a deprecated software framework from Microsoft for downloading content from a network?",
    "directx": "What is Microsoft's API for multimedia, game programming, and video?",
    "netframework": "What is Microsoft's software framework that runs primarily on Windows?",
    "powershellise": "What is the integrated scripting environment for PowerShell?",
    "uac": "What does UAC stand for in Windows security?",
    "winsxs": "What is the component store in Windows?",
    "wsl": "What allows you to run Linux distributions on Windows?",
    "ntfs": "What is the default file system for Windows NT and later?",
    "fat32": "What is a widely compatible file system, but with limitations on file and partition size?",
    "exfat": "What file system is optimized for flash memory such as USB flash drives and SD cards?",
    "defrag": "What utility in Windows rearranges fragmented data?",
    # 600+ new words
    "hypervisor": "Software that creates and runs virtual machines.",
    "container": "A lightweight, standalone, executable package of software that includes everything needed to run it.",
    "kubernetes": "An open-source system for automating deployment, scaling, and management of containerized applications.",
    "docker": "A set of platform-as-a-service products that use OS-level virtualization to deliver software in packages called containers.",
    "ansible": "An open-source software provisioning, configuration management, and application-deployment tool.",
    "puppet": "A software configuration management tool which includes its own declarative language to describe system configuration.",
    "chef": "A configuration management tool written in Ruby and Erlang.",
    "vagrant": "A tool for building and managing virtual machine environments in a single workflow.",
    "terraform": "An open-source infrastructure as code software tool.",
    "jenkins": "An open-source automation server which enables developers to reliably build, test, and deploy their software.",
    "nagios": "A popular open-source computer-software application that monitors systems, networks and infrastructure.",
    "zabbix": "An open-source monitoring software tool for diverse IT components, including networks, servers, virtual machines and cloud services.",
    "prometheus": "An open-source systems monitoring and alerting toolkit.",
    "grafana": "An open-source platform for monitoring and observability.",
    "elk": "A combination of three open-source tools—Elasticsearch, Logstash, and Kibana—used for searching, analyzing, and visualizing log data.",
    "spam": "Unsolicited or undesired electronic messages.",
    "phishing": "A fraudulent attempt to obtain sensitive information such as usernames, passwords and credit card details by disguising as a trustworthy entity in an electronic communication.",
    "vlan": "A virtual LAN is any broadcast domain that is partitioned and isolated in a computer network at the data link layer.",
    "nat": "A method of remapping an IP address space into another by modifying network address information in the IP header of packets while they are in transit across a traffic routing device.",
    "dhcp": "A network management protocol used on Internet Protocol networks for automatically assigning IP addresses and other communication parameters to devices connected to the network.",
    "dns": "A hierarchical and decentralized naming system for computers, services, or other resources connected to the Internet or a private network.",
    "smtp": "A communication protocol for electronic mail transmission.",
    "pop3": "A standard mail protocol used to receive emails from a remote server to a local email client.",
    "imap": "A mail protocol used to access email on a remote mail server from a local client.",
    "http": "The foundation of data communication for the World Wide Web.",
    "https": "An extension of the Hypertext Transfer Protocol for secure communication over a computer network.",
    "ftp": "A standard network protocol used for the transfer of computer files between a client and server on a computer network.",
    "sftp": "A network protocol that provides file access, file transfer, and file management over any reliable data stream.",
    "scp": "A means of securely transferring computer files between a local host and a remote host or between two remote hosts.",
    "ssl": "A standard security technology for establishing an encrypted link between a server and a client.",
    "tls": "A cryptographic protocol that provides end-to-end communications security over networks.",
    "ssh-keygen": "A tool for creating new authentication key pairs for SSH.",
    "tcpdump": "A powerful command-line packet analyzer.",
    "wireshark": "A free and open-source packet analyzer.",
    "nmap": "A free and open-source network scanner.",
    "metasploit": "A popular open-source penetration testing framework.",
    "burp-suite": "A graphical tool for testing Web application security.",
    "owasp": "An online community that produces freely-available articles, methodologies, documentation, tools, and technologies in the field of web application security.",
    "cve": "A list of publicly disclosed computer security flaws.",
    "sql-injection": "A code injection technique that might destroy your database.",
    "cross-site-scripting": "A type of security vulnerability typically found in web applications.",
    "csrf": "An attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated.",
    "denial-of-service": "A cyber-attack in which the perpetrator seeks to make a machine or network resource unavailable to its intended users.",
    "distributed-denial-of-service": "A cyber-attack in which the perpetrator uses more than one unique IP address, often thousands of them.",
    "man-in-the-middle": "An attack where the attacker secretly relays and possibly alters the communication between two parties who believe they are directly communicating with each other.",
    "zero-day": "A vulnerability that is unknown to those who should be interested in mitigating it.",
    "exploit": "A piece of software, a chunk of data, or a sequence of commands that takes advantage of a bug or vulnerability.",
    "fuzzing": "An automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program.",
    "honeypot": "A computer security mechanism set to detect, deflect, or, in some manner, counteract attempts at unauthorized use of information systems.",
    "intrusion-detection-system": "A device or software application that monitors a network or systems for malicious activity or policy violations.",
    "intrusion-prevention-system": "A network security/threat prevention technology that examines network traffic flows to detect and prevent vulnerability exploits.",
    "load-balancer": "A device that acts as a reverse proxy and distributes network or application traffic across a number of servers.",
    "failover": "A backup operational mode in which the functions of a system component are assumed by secondary system components when the primary component becomes unavailable.",
    "high-availability": "A characteristic of a system, which aims to ensure an agreed level of operational performance, usually uptime, for a higher than normal period.",
    "disaster-recovery": "A set of policies, tools and procedures to enable the recovery or continuation of vital technology infrastructure and systems following a natural or human-induced disaster.",
    "backup": "A copy of computer data taken and stored elsewhere so that it may be used to restore the original after a data loss event.",
    "restore": "To return something to a former condition.",
    "data-integrity": "The maintenance of, and the assurance of the accuracy and consistency of, data over its entire life-cycle.",
    "data-redundancy": "A condition created within a database or data storage technology in which the same piece of data is held in two separate places.",
    "raid": "A data storage virtualization technology that combines multiple physical disk drive components into one or more logical units for the purposes of data redundancy, performance improvement, or both.",
    "san": "A storage area network is a computer network which provides access to consolidated, block-level data storage.",
    "nas": "A network-attached storage is a file-level computer data storage server connected to a computer network providing data access to a heterogeneous group of clients.",
    "das": "Direct-attached storage is digital storage directly attached to the computer accessing it, as opposed to storage accessed over a computer network.",
    "iscsi": "An IP-based storage networking standard for linking data storage facilities.",
    "fibre-channel": "A high-speed data transfer protocol providing in-order, lossless delivery of raw block data.",
    "infiniband": "A computer-networking communications standard used in high-performance computing.",
    "ethernet-fabric": "A layer 2 network topology where devices are connected to each other through a switch or a set of switches.",
    "spine-leaf": "A two-layer network topology composed of spine switches and leaf switches.",
    "sdn": "Software-defined networking is an umbrella term encompassing several kinds of network technology aimed at making the network as agile and flexible as the virtualized server and storage infrastructure of the modern data center.",
    "nfv": "Network functions virtualization is a network architecture concept that uses the technologies of IT virtualization to virtualize entire classes of network node functions into building blocks that may connect, or be chained together, to create communication services.",
    "api-gateway": "An API management tool that sits between a client and a collection of backend services.",
    "service-mesh": "A dedicated infrastructure layer for handling service-to-service communication.",
    "microservices": "An architectural style that structures an application as a collection of services.",
    "monolithic-architecture": "A traditional unified model for the design of a software program.",
    "serverless": "A cloud-computing execution model in which the cloud provider runs the server, and dynamically manages the allocation of machine resources.",
    "cloud-native": "An approach to building and running applications that exploits the advantages of the cloud computing delivery model.",
    "devops": "A set of practices that combines software development and IT operations.",
    "devsecops": "The philosophy of integrating security practices within the DevOps process.",
    "ci-cd": "The combined practices of continuous integration and either continuous delivery or continuous deployment.",
    "continuous-integration": "The practice of merging all developer working copies to a shared mainline several times a day.",
    "continuous-delivery": "A software engineering approach in which teams produce software in short cycles, ensuring that the software can be reliably released at any time.",
    "continuous-deployment": "A software release process that uses automated testing to validate if changes to a codebase are correct and stable for immediate autonomous deployment to a production environment.",
    "agile-methodology": "A type of project management process, mainly used for software development, where demands and solutions evolve through the collaborative effort of self-organizing and cross-functional teams and their customer(s)/end user(s).",
    "kanban": "A lean method to manage and improve work across human systems.",
    "lean-methodology": "A production practice that considers the expenditure of resources for any goal other than the creation of value for the end customer to be wasteful, and thus a target for elimination.",
    "six-sigma": "A set of techniques and tools for process improvement.",
    "waterfall-model": "A breakdown of project activities into linear sequential phases, where each phase depends on the deliverables of the previous one and corresponds to a specialisation of tasks.",
    "pair-programming": "An agile software development technique in which two programmers work together at one workstation.",
    "mob-programming": "A software development approach where the whole team works on the same thing, at the same time, in the same space, and at the same computer.",
    "code-review": "A software quality assurance activity in which one or several humans check a program mainly by viewing and reading parts of its source code.",
    "technical-debt": "The implied cost of rework caused by choosing an easy (limited) solution now instead of using a better approach that would take longer.",
    "refactoring-guru": "A popular website that provides information on refactoring and design patterns.",
    "design-patterns": "A general reusable solution to a commonly occurring problem within a given context in software design.",
    "singleton-pattern": "A design pattern that restricts the instantiation of a class to one object.",
    "factory-pattern": "A creational pattern that provides an interface for creating objects in a superclass, but allows subclasses to alter the type of objects that will be created.",
    "observer-pattern": "A behavioral design pattern that lets you define a subscription mechanism to notify multiple objects about any events that happen to the object they’re observing.",
    "decorator-pattern": "A design pattern that allows behavior to be added to an individual object, either statically or dynamically, without affecting the behavior of other objects from the same class.",
    "strategy-pattern": "A behavioral software design pattern that enables selecting an algorithm at runtime.",
    "adapter-pattern": "A software design pattern that allows the interface of an existing class to be used as another interface.",
    "facade-pattern": "A software design pattern that provides a simplified interface to a large body of code.",
    "command-pattern": "A behavioral design pattern in which an object is used to encapsulate all information needed to perform an action or trigger an event at a later time.",
    "template-method-pattern": "A behavioral design pattern that defines the program skeleton of an algorithm in an operation, deferring some steps to subclasses.",
    "iterator-pattern": "A design pattern in which an iterator is used to traverse a container and access the container's elements.",
    "composite-pattern": "A partitioning design pattern.",
    "proxy-pattern": "A design pattern in which a class represents the functionality of another class.",
    "bridge-pattern": "A software design pattern that is used to decouple an abstraction from its implementation so that the two can vary independently.",
    "flyweight-pattern": "A software design pattern that is used when we need to create a lot of Objects of a class.",
    "mediator-pattern": "A design pattern that is used to reduce coupling between components of a program.",
    "memento-pattern": "A software design pattern that provides the ability to restore an object to its previous state.",
    "state-pattern": "A behavioral software design pattern that allows an object to alter its behavior when its internal state changes.",
    "visitor-pattern": "A way of separating an algorithm from an object structure on which it operates.",
    "interpreter-pattern": "A behavioral design pattern that is used to define a grammatical representation for a language and provides an interpreter to deal with this grammar.",
    "chain-of-responsibility-pattern": "A design pattern consisting of a source of command objects and a series of processing objects.",
    "solid": "A mnemonic acronym for five design principles intended to make software designs more understandable, flexible, and maintainable.",
    "single-responsibility-principle": "A computer programming principle that states that every module, class, or function should have responsibility over a single part of the functionality provided by the software.",
    "open-closed-principle": "A principle of object-oriented design that states that software entities (classes, modules, functions, etc.) should be open for extension, but closed for modification.",
    "liskov-substitution-principle": "A principle in object-oriented programming stating that, in a computer program, if S is a subtype of T, then objects of type T may be replaced with objects of type S.",
    "interface-segregation-principle": "A principle of software design that states that no client should be forced to depend on methods it does not use.",
    "dependency-inversion-principle": "A specific form of decoupling software modules.",
    "dry": "A principle of software development aimed at reducing repetition of software patterns, replacing it with abstractions or using data normalization to avoid redundancy.",
    "kiss": "A design principle which states that most systems work best if they are kept simple rather than made complicated.",
    "yagni": "A principle of extreme programming that states a programmer should not add functionality until it is deemed necessary.",
    "big-ball-of-mud": "A software system that lacks a perceivable architecture.",
    "spaghetti-code": "A pejorative phrase for source code that has a complex and tangled control structure.",
    "lasagna-code": "A type of program that is structured into a number of layers.",
    "ravioli-code": "A term for code that is made up of a number of small, loosely coupled components.",
    "magic-numbers": "A numeric literal that is used in the middle of a block of code without explanation.",
    "hard-coding": "The software development practice of embedding data directly into the source code of a program or other executable object, as opposed to obtaining the data from external sources or generating it at runtime.",
    "soft-coding": "The practice of moving application logic and behavior out of source code and into a configuration file, database, or other external source.",
    "camel-case": "The practice of writing phrases such that each word or abbreviation in the middle of the phrase begins with a capital letter, with no intervening spaces or punctuation.",
    "pascal-case": "A naming convention in which the first letter of each word in a compound word is capitalized.",
    "snake-case": "The practice of writing compound words or phrases in which the elements are separated with one underscore character and no spaces.",
    "kebab-case": "The practice of writing identifiers in which the words are separated by hyphens.",
    "git-clone": "A Git command which creates a copy of an existing Git repository.",
    "git-pull": "A Git command used to update the local version of a repository from a remote.",
    "git-push": "A Git command that is used to upload local repository content to a remote repository.",
    "git-commit": "A Git command that's used to save your changes to the local repository.",
    "git-add": "A Git command that adds a change in the working directory to the staging area.",
    "git-status": "A Git command that displays the state of the working directory and the staging area.",
    "git-branch": "A Git command that lets you create, list, rename, and delete branches.",
    "git-checkout": "A Git command that lets you navigate between the branches created by git branch.",
    "git-merge": "A Git command that lets you take the independent lines of development created by git branch and integrate them into a single branch.",
    "git-rebase": "A Git command that is used to re-apply commits on top of another base tip.",
    "git-log": "A Git command that is used to show the commit history of a repository.",
    "git-diff": "A Git command that is used to show the changes between commits, commit and working tree, etc.",
    "git-tag": "A Git command that is used to create, list, delete or verify a tag object signed with GPG.",
    "git-remote": "A Git command that lets you create, view, and delete connections to other repositories.",
    "git-fetch": "A Git command that downloads commits, files, and refs from a remote repository into your local repo.",
    "github": "A provider of Internet hosting for software development and version control using Git.",
    "gitlab": "A web-based DevOps lifecycle tool that provides a Git-repository manager providing wiki, issue-tracking and CI/CD pipeline features.",
    "bitbucket": "A Git-based source code repository hosting service owned by Atlassian.",
    "svn": "A software versioning and revision control system.",
    "mercurial": "A distributed revision-control tool for software developers.",
    "bazaar": "A distributed and client-server revision control system.",
    "monorepo": "A software development strategy where code for many projects is stored in the same repository.",
    "polyrepo": "The practice of using multiple repositories to manage code.",
    "agpl": "A free software license that requires the source code to be made available when the software is used over a network.",
    "gpl": "A series of widely-used free software licenses that guarantee end users the four freedoms to run, study, share, and modify the software.",
    "lgpl": "A free-software license published by the Free Software Foundation.",
    "mit-license": "A permissive free software license originating at the Massachusetts Institute of Technology.",
    "apache-license": "A permissive free software license written by the Apache Software Foundation.",
    "bsd-license": "A family of permissive free software licenses, imposing minimal restrictions on the use and distribution of covered software.",
    "c-programming-language": "A general-purpose, procedural computer programming language.",
    "c-plus-plus": "A general-purpose programming language created as an extension of the C programming language.",
    "java": "A high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
    "javascript": "A programming language that conforms to the ECMAScript specification.",
    "typescript": "A strict syntactical superset of JavaScript and adds optional static typing to the language.",
    "ruby": "A dynamic, open source programming language with a focus on simplicity and productivity.",
    "php": "A general-purpose scripting language especially suited to web development.",
    "go": "A statically typed, compiled programming language designed at Google.",
    "rust": "A multi-paradigm, general-purpose programming language designed for performance and safety, especially safe concurrency.",
    "swift": "A general-purpose, multi-paradigm, compiled programming language developed by Apple Inc.",
    "kotlin": "A cross-platform, statically typed, general-purpose programming language with type inference.",
    "scala": "A strong statically typed general-purpose programming language that supports both object-oriented and functional programming.",
    "perl": "A family of two high-level, general-purpose, interpreted, dynamic programming languages.",
    "haskell": "A general-purpose, statically typed, purely functional programming language with type inference and lazy evaluation.",
    "lisp": "A family of programming languages with a long history and a distinctive, fully parenthesized prefix notation.",
    "clojure": "A dynamic, general-purpose programming language, combining the approachability and interactive development of a scripting language with an efficient and robust infrastructure for multithreaded programming.",
    "erlang": "A general-purpose, concurrent, functional programming language, and a garbage-collected runtime system.",
    "elixir": "A dynamic, functional language designed for building scalable and maintainable applications.",
    "f-sharp": "A functional-first, general purpose, strongly typed, multi-paradigm programming language that encompasses functional, imperative, and object-oriented programming methods.",
    "objective-c": "A general-purpose, object-oriented programming language that adds Smalltalk-style messaging to the C programming language.",
    "dart": "A programming language designed for client development, such as for the web and mobile apps.",
    "r-programming-language": "A programming language and free software environment for statistical computing and graphics.",
    "matlab": "A proprietary multi-paradigm programming language and numeric computing environment developed by MathWorks.",
    "assembly-language": "A low-level programming language for a computer, or other programmable device, in which there is a very strong correspondence between the instructions in the language and the architecture's machine code instructions.",
    "html": "The standard markup language for documents designed to be displayed in a web browser.",
    "css3": "The latest evolution of the Cascading Style Sheets language.",
    "sass": "A preprocessor scripting language that is interpreted or compiled into Cascading Style Sheets.",
    "less-css": "A dynamic style sheet language that can be compiled into Cascading Style Sheets and run on the client side or server side.",
    "bootstrap": "A free and open-source CSS framework directed at responsive, mobile-first front-end web development.",
    "tailwind-css": "A utility-first CSS framework for rapidly building custom user interfaces.",
    "material-ui": "A popular React UI framework.",
    "ant-design": "A design system for enterprise-level products.",
    "react": "A free and open-source front-end JavaScript library for building user interfaces or UI components.",
    "angular": "A TypeScript-based open-source web application framework led by the Angular Team at Google.",
    "vue-js": "An open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications.",
    "svelte": "A free and open-source front-end compiler created by Rich Harris and maintained by the Svelte core team members.",
    "ember-js": "An open-source JavaScript web framework, based on the Model-view-viewmodel pattern.",
    "backbone-js": "A JavaScript library with a RESTful JSON interface and is based on the model–view–presenter application design paradigm.",
    "jquery": "A fast, small, and feature-rich JavaScript library.",
    "node-js": "An open-source, cross-platform, back-end JavaScript runtime environment that runs on the V8 engine and executes JavaScript code outside a web browser.",
    "express-js": "A back end web application framework for Node.js.",
    "django": "A Python-based free and open-source web framework that follows the model-template-views architectural pattern.",
    "flask": "A micro web framework written in Python.",
    "fastapi": "A modern, fast (high-performance), web framework for building APIs with Python 3.6+ based on standard Python type hints.",
    "ruby-on-rails": "A server-side web application framework written in Ruby under the MIT License.",
    "laravel": "A free, open-source PHP web framework, created by Taylor Otwell and intended for the development of web applications following the model–view–controller architectural pattern.",
    "symfony": "A PHP web application framework and a set of reusable PHP components/libraries.",
    "spring-boot": "An open source Java-based framework used to create a micro Service.",
    "asp-net": "An open-source, server-side web-application framework designed for web development to produce dynamic web pages.",
    "phoenix-framework": "A web development framework written in the functional programming language Elixir.",
    "graphql": "An open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data.",
    "rest": "An architectural style for providing standards between computer systems on the web, making it easier for systems to communicate with each other.",
    "soap": "A messaging protocol specification for exchanging structured information in the implementation of web services in computer networks.",
    "json": "An open standard file format, and data interchange format, that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and array data types.",
    "xml": "A markup language and file format for storing, transmitting, and reconstructing arbitrary data.",
    "yaml": "A human-readable data-serialization language.",
    "csv": "A comma-separated values file is a delimited text file that uses a comma to separate values.",
    "openapi": "A specification for machine-readable interface files for describing, producing, consuming, and visualizing RESTful web services.",
    "swagger": "An open-source software framework backed by a large ecosystem of tools that helps developers design, build, document, and consume RESTful web services.",
    "jwt": "A proposed Internet standard for creating data with optional signature and/or optional encryption whose payload holds JSON that asserts some number of claims.",
    "oauth": "An open standard for access delegation, commonly used as a way for Internet users to grant websites or applications access to their information on other websites but without giving them the passwords.",
    "saml": "An open standard for exchanging authentication and authorization data between parties, in particular, between an identity provider and a service provider.",
    "openid": "An open standard and decentralized authentication protocol.",
    "kerberos": "A computer-network authentication protocol that works on the basis of 'tickets' to allow nodes communicating over a non-secure network to prove their identity to one another in a secure manner.",
    "ldap": "An open, vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services over an Internet Protocol network.",
    "active-directory": "A directory service developed by Microsoft for Windows domain networks.",
    "x-509": "A standard defining the format of public key certificates.",
    "certificate-authority": "An entity that issues digital certificates.",
    "public-key-infrastructure": "A set of roles, policies, hardware, software and procedures needed to create, manage, distribute, use, store and revoke digital certificates and manage public-key encryption.",
    "encryption": "The process of converting information or data into a code, especially to prevent unauthorized access.",
    "decryption": "The process of taking encoded or encrypted text and converting it back into text that you or the computer can read and understand.",
    "symmetric-encryption": "A type of encryption where only one key (a secret key) is used to both encrypt and decrypt electronic information.",
    "asymmetric-encryption": "A type of encryption that uses two different but mathematically linked keys, one public and one private.",
    "aes": "A symmetric block cipher chosen by the U.S. government to protect classified information.",
    "des": "A symmetric-key algorithm for the encryption of electronic data.",
    "rsa": "A public-key cryptosystem that is widely used for secure data transmission.",
    "diffie-hellman": "A method of securely exchanging cryptographic keys over a public channel and was one of the first public-key protocols as conceived by Ralph Merkle.",
    "elliptic-curve-cryptography": "An approach to public-key cryptography based on the algebraic structure of elliptic curves over finite fields.",
    "hashing": "The process of transforming any given key or a string of characters into another value.",
    "md5": "A widely used hash function producing a 128-bit hash value.",
    "sha-1": "A cryptographic hash function which takes an input and produces a 160-bit hash value.",
    "sha-256": "A patented cryptographic hash function that outputs a value of 256 bits.",
    "bcrypt": "A password-hashing function designed by Niels Provos and David Mazières, based on the Blowfish cipher.",
    "scrypt": "A password-based key derivation function created by Colin Percival, originally for the Tarsnap online backup service.",
    "argon2": "A key derivation function that was selected as the winner of the Password Hashing Competition in July 2015.",
    "salting": "A technique to protect passwords stored in databases by adding a random string of characters to each password before it is hashed.",
    "peppering": "A secret value that is added to a user's password before it is hashed.",
    "rainbow-table": "A precomputed table for reversing cryptographic hash functions, usually for cracking password hashes.",
    "brute-force-attack": "A trial-and-error method used by application programs to decode encrypted data such as passwords or Data Encryption Standard keys, through exhaustive effort rather than employing intellectual strategies.",
    "dictionary-attack": "A method of breaking into a password-protected computer or server by systematically entering every word in a dictionary as a password.",
    "emacs": "A family of text editors that are characterized by their extensibility.",
    "vim": "A highly configurable text editor for efficiently creating and changing any kind of text.",
    "nano": "A text editor for Unix-like computing systems or operating environments using a command line interface.",
    "visual-studio-code": "A free source-code editor made by Microsoft for Windows, Linux and macOS.",
    "sublime-text": "A shareware cross-platform source code editor with a Python application programming interface.",
    "atom": "A free and open-source text and source code editor for macOS, Linux, and Microsoft Windows with support for plug-ins written in JavaScript, and embedded Git Control.",
    "intellij-idea": "An integrated development environment written in Java for developing computer software.",
    "eclipse": "An integrated development environment used in computer programming.",
    "xcode": "An integrated development environment for macOS containing a suite of software development tools developed by Apple for developing software for macOS, iOS, iPadOS, watchOS, and tvOS.",
    "android-studio": "The official integrated development environment for Google's Android operating system, built on JetBrains' IntelliJ IDEA software and designed specifically for Android development.",
    "virtualbox": "A free and open-source hosted hypervisor for x86 virtualization, developed by Oracle Corporation.",
    "vmware": "A company that provides cloud computing and virtualization software and services.",
    "qemu": "A free and open-source emulator and virtualizer that can perform hardware virtualization.",
    "kvm": "A virtualization module in the Linux kernel that allows the kernel to function as a hypervisor.",
    "xen": "A type-1 hypervisor, providing services that allow multiple computer operating systems to execute on the same computer hardware concurrently.",
    "hyper-v": "A native hypervisor; it can create virtual machines on x86-64 systems running Windows.",
    "lxc": "An operating-system-level virtualization method for running multiple isolated Linux systems on a control host using a single Linux kernel.",
    "lxd": "A next generation system container manager.",
    "systemd": "A software suite that provides an array of system components for Linux operating systems.",
    "init": "The first process started during booting of the computer system.",
    "runit": "A cross-platform Unix init scheme with service supervision.",
    "s6": "A small and secure supervision suite.",
    "openrc": "A dependency-based init system for Unix-like computer operating systems.",
    "upstart": "An event-based replacement for the /sbin/init daemon which handles starting of tasks and services during boot, stopping them during shutdown and supervising them while the system is running.",
    "sysvinit": "The classic init system for Unix System V.",
    "grub": "A boot-loader package from the GNU Project.",
    "lilo": "A boot loader for Linux and was the default boot loader for most Linux distributions in the years after the popularity of loadlin.",
    "systemd-boot": "A simple UEFI boot manager.",
    "refind": "A boot manager for UEFI-based computers.",
    "clover": "An operating system boot loader for computers that use UEFI or BIOS firmware.",
    "opencore": "A free and open-source boot loader designed to be a more secure, modern, and flexible alternative to Clover.",
    "bash-script": "A script written for the bash shell.",
    "shell-script": "A computer program designed to be run by the Unix shell, a command-line interpreter.",
    "powershell-script": "A script written for the PowerShell command-line shell and scripting language.",
    "batch-file": "A script file in DOS, OS/2 and Microsoft Windows.",
    "makefile": "A file containing a set of directives used by a make build automation tool to generate a target/goal.",
    "dockerfile": "A text document that contains all the commands a user could call on the command line to assemble an image.",
    "yaml-file": "A file that uses a human-readable data-serialization language.",
    "json-file": "A file that uses a human-readable data-serialization language.",
    "xml-file": "A file that uses a markup language and file format for storing, transmitting, and reconstructing arbitrary data.",
    "ini-file": "A configuration file for computer software that consists of a text-based content with a structure and syntax comprising sections, properties, and values.",
    "conf-file": "A configuration file.",
    "toml": "A configuration file format.",
    "log-file": "A file that records either events that occur in an operating system or other software runs, or messages between different users of a communication software.",
    "binary-file": "A computer file that is not a text file.",
    "text-file": "A kind of computer file that is structured as a sequence of lines of electronic text.",
    "executable-file": "A computer file that contains a program, that is, a particular kind of file that is capable of being executed or run as a program in the computer.",
    "shared-library": "A file containing object code that several a.out files may use simultaneously while executing.",
    "static-library": "A set of routines, external functions and variables which are resolved in a caller at compile-time and copied into a target application by a compiler, linker, or binder, producing an object file and a stand-alone executable.",
    "dll": "Microsoft's implementation of the shared library concept in the Microsoft Windows and OS/2 operating systems.",
    "so-file": "A shared object file.",
    "a-file": "An archive file.",
    "o-file": "An object file.",
    "c-file": "A C source file.",
    "cpp-file": "A C++ source file.",
    "h-file": "A C/C++ header file.",
    "py-file": "A Python source file.",
    "js-file": "A JavaScript source file.",
    "ts-file": "A TypeScript source file.",
    "rb-file": "A Ruby source file.",
    "php-file": "A PHP source file.",
    "go-file": "A Go source file.",
    "rs-file": "A Rust source file.",
    "swift-file": "A Swift source file.",
    "kt-file": "A Kotlin source file.",
    "java-file": "A Java source file.",
    "class-file": "A file containing Java bytecode that can be executed on the Java Virtual Machine.",
    "jar-file": "A package file format typically used to aggregate many Java class files and associated metadata and resources into one file for distribution.",
    "war-file": "A file used to distribute a collection of JavaServer Pages, servlets, Java classes, XML files, tag libraries, static web pages and other resources that together constitute a web application.",
    "ear-file": "A file format used by Java EE for packaging one or more modules into a single archive so that the deployment of the various modules onto an application server happens simultaneously.",
    "zip-file": "An archive file format that supports lossless data compression.",
    "tar-file": "A kind of archive file.",
    "gz-file": "A file compressed with gzip.",
    "bz2-file": "A file compressed with bzip2.",
    "xz-file": "A file compressed with xz.",
    "7z-file": "A compressed archive file format that supports several different data compression, encryption and pre-processing algorithms.",
    "rar-file": "A proprietary archive file format that supports data compression, error recovery and file spanning.",
    "iso-file": "A disk image of an optical disc.",
    "img-file": "A disk image.",
    "dmg-file": "A disk image format used by macOS.",
    "exe-file": "An executable file for Microsoft Windows.",
    "msi-file": "An installer package file format used by Windows.",
    "deb-file": "A software package format for Debian and its derivatives.",
    "rpm-file": "A package file format used by Red Hat and its derivatives.",
    "appimage": "A format for distributing portable software on Linux without needing superuser permissions to install the application.",
    "flatpak": "A utility for software deployment and package management for Linux.",
    "snap": "A software packaging and deployment system developed by Canonical for operating systems that use the Linux kernel.",
    "apt-get": "A command-line tool which helps in handling packages in Linux.",
    "apt-cache": "A command-line tool for searching the apt package cache.",
    "dpkg": "The package manager for Debian and its derivatives.",
    "yum-command": "The default package manager for CentOS and other Red Hat-based Linux distributions.",
    "rpm-command": "A powerful package management system used by Red Hat Linux and its derivatives such as CentOS and Fedora.",
    "dnf": "The next-generation version of YUM, a package manager for RPM-based Linux distributions.",
    "pacman-command": "The package manager for Arch Linux.",
    "emerge": "The command-line interface to the Portage package management system.",
    "portage": "The package management system for Gentoo Linux.",
    "brew": "A free and open-source software package management system that simplifies the installation of software on Apple's macOS operating system and Linux.",
    "chocolatey": "A machine-level package manager for Windows.",
    "scoop": "A command-line installer for Windows.",
    "winget": "A free and open-source package manager designed by Microsoft for Windows 10 and Windows 11.",
    "petabyte": "What is 1024 terabytes?",
    "exabyte": "What is 1024 petabytes?",
    "zettabyte": "What is 1024 exabytes?",
    "yottabyte": "What is 1024 zettabytes?",
    "sata": "A command and bus interface that connects host bus adapters to mass storage devices.",
    "nvme": "A specification for accessing SSDs attached through the PCIe bus.",
    "pcie": "A high-speed serial computer expansion bus standard.",
    "agp": "A parallel expansion card standard, designed for attaching a video card to a computer system.",
    "isa": "The 16-bit internal bus of IBM PC/AT and similar computers based on the Intel 80286 and its immediate successors.",
    "pci": "A local computer bus for attaching hardware devices in a computer.",
    "cmos": "A technology for constructing integrated circuits.",
    "jumper": "A short length of conductor used to close, open or bypass part of an electronic circuit.",
    "northbridge": "One of the two chips in the core logic chipset on a PC motherboard.",
    "southbridge": "One of the two chips in the core logic chipset on a PC motherboard.",
    "chipset": "A set of electronic components in an integrated circuit known as a 'Data Flow Management System' that manages the data flow between the processor, memory and peripherals.",
    "multicore": "A single computing component with two or more independent actual processing units.",
    "hyperthreading": "Intel's proprietary simultaneous multithreading implementation used to improve parallelization of computations.",
    "overclocking": "The action of increasing a component's clock rate, running it at a higher speed than it was designed to run.",
    "underclocking": "To run a computer or its components at a lower clock rate than specified.",
    "voltage": "The difference in electric potential between two points.",
    "amperage": "The strength of an electric current in amperes.",
    "wattage": "The amount of electrical power expressed in watts.",
    "displayport": "A digital display interface developed by a consortium of chip and monitor manufacturers.",
    "thunderbolt": "A hardware interface that allows the connection of external peripherals to a computer.",
    "usb-c": "A 24-pin USB connector system, which is distinguished by its two-fold rotationally-symmetrical connector.",
    "joystick": "An input device consisting of a stick that pivots on a base and reports its angle or direction to the device it is controlling.",
    "webcam": "A video camera that feeds or streams its image in real time to or through a computer to a computer network.",
    "soundcard": "An internal expansion card that provides input and output of audio signals to and from a computer under control of computer programs.",
    "raid0": "A RAID configuration that uses striping to provide improved performance, but no redundancy.",
    "raid1": "A RAID configuration that uses mirroring to provide redundancy.",
    "raid5": "A RAID configuration that uses striping with parity to provide both performance and redundancy.",
    "raid6": "A RAID configuration that uses striping with double parity to provide fault tolerance of up to two-drive failures.",
    "raid10": "A RAID configuration that combines mirroring and striping to protect data from a single drive failure.",
    "jbod": "A tier of storage in a computer system that is 'just a bunch of disks'.",
    "hot-swapping": "The replacement or addition of components to a computer system without stopping, shutting down, or rebooting the system.",
}
